"""einhander default assembly.

Places every part by params / mates (no hand-tuned Pos in the layout beyond the
datums the layout legitimately owns), exports per-part STLs, writes a colored
.scad, and renders iso + thumb-side PNGs with OpenSCAD.

    python3 machine.py            # build STLs + .scad + renders
"""

import os
import subprocess
from functools import reduce

from build123d import Pos, Compound, export_stl

import machine_params as M
import top_shell
import bottom_shell
import components as C

HERE = os.path.dirname(os.path.abspath(__file__))
BUILD = os.path.join(HERE, "build")

# (name, [r,g,b], world solid) -------------------------------------------------
GREY_T = [0.86, 0.87, 0.90]
GREY_B = [0.42, 0.45, 0.52]
DARK = [0.16, 0.18, 0.22]
CYAN = [0.10, 0.78, 0.82]      # the project's "active / value" accent
RED = [0.86, 0.28, 0.30]
GREEN = [0.10, 0.45, 0.22]


def assembly_parts():
    parts = []

    # shells — placed at the datums the layout owns
    parts.append(("bottom_shell", GREY_B, Pos(0, 0, 0) * bottom_shell.part()))
    parts.append(("top_shell", GREY_T, Pos(0, 0, M.SEAM_Z) * top_shell.part()))

    # PCB blank
    parts.append(("pcb", GREEN, Pos(0, 0, M.PCB_BOT_Z) * C.pcb()))

    # 8 switches + keycaps
    for i, (kx, ky) in enumerate(M.KEY_XY):
        parts.append((f"switch_{i}", DARK,
                      Pos(kx, ky, M.DECK_TOP_Z) * C.switch()))

    # thumb cluster
    parts.append(("thumbwheel", CYAN,
                  Pos(M.WHEEL_CX, M.WHEEL_Y, M.WHEEL_Z) * C.thumbwheel()))
    parts.append(("button", RED,
                  Pos(-M.BODY_X / 2, M.BTN_Y, M.BTN_Z) * C.button()))

    return parts


def main():
    os.makedirs(BUILD, exist_ok=True)
    parts = assembly_parts()

    # manifest + export
    print("part                 bbox (mm)")
    for name, _rgb, solid in parts:
        export_stl(solid, os.path.join(BUILD, f"{name}.stl"))
        bb = solid.bounding_box()
        print(f"  {name:18s} {bb.size.X:5.1f} {bb.size.Y:5.1f} {bb.size.Z:5.1f}")

    whole = Compound(children=[s for _n, _c, s in parts])
    bb = whole.bounding_box()
    print(f"\nassembly bbox: {bb.size.X:.1f} x {bb.size.Y:.1f} x {bb.size.Z:.1f} mm "
          f"(+ keycaps to z={bb.max.Z:.1f})")
    export_stl(whole, os.path.join(BUILD, "einhander.stl"))

    # colored .scad
    lines = ["// auto-generated by machine.py — do not edit", "$fn=64;"]
    for name, rgb, _s in parts:
        r, g, b = rgb
        lines.append(f'color([{r},{g},{b}]) import("{name}.stl");')
    scad = os.path.join(BUILD, "einhander.scad")
    with open(scad, "w") as f:
        f.write("\n".join(lines) + "\n")

    # renders
    views = {
        "iso": (55, 0, 25),        # over-the-shoulder, shows deck + thumb side
        "thumb": (72, 0, 200),     # swing around to face the left (thumb) wall
        "top": (0, 0, 0),          # plan view of the key deck
    }
    for vname, (rx, ry, rz) in views.items():
        out = os.path.join(BUILD, f"einhander_{vname}.png")
        cam = f"0,0,0,{rx},{ry},{rz},0"
        cmd = ["openscad", "-o", out, "--imgsize=1500,1100",
               "--projection=perspective", "--colorscheme=Tomorrow",
               "--autocenter", "--viewall", f"--camera={cam}", scad]
        r = subprocess.run(cmd, capture_output=True, text=True)
        status = "ok" if r.returncode == 0 and os.path.exists(out) else "FAIL"
        print(f"render {vname:6s} -> {out}  [{status}]")
        if status == "FAIL":
            print(r.stderr[-500:])


if __name__ == "__main__":
    main()
